### ISSUE TITLE
vendor "golang.org/x/net/trace" is out of date

### ISSUE THREAD

**Issue by yogaganesha** [bketelsen/crypt#5]
Hi,

one of the dependency using "github.com/bketelsen/crypt" which is breaking the build.
Going by the error below vendor package need to be updated.

Thanks
Yoga

_Error_ _log:
panic: /debug/requests is already registered. You may have two independent copies of golang.org/x/net/trace in your binary, trying to maintain separate state. This may involve a vendored copy of golang.org/x/net/trace.

**Comment by alxmsl** [comment]
@yogaganesha could you share more information about your setup? Which libraries are you including? Could you share some code, please?

**Comment by yogaganesha** [comment]
@alxmsl 
Thanks for the response. it was a transitive dependency. We use hashicorp/consul which uses github.com/bketelsen/crypt package.
I was not using "go modules", resolved this issue by adding go modules.

Thanks
