### ISSUE TITLE
Add token to Consul API

### ISSUE THREAD

**Issue by sabir012** [bketelsen/crypt#8]
Hi, I am using Viper in order to use Consul for KV storage.  Viper uses crypt in order to connect remote providers. However, I am using ACL in Consul and need to attach token to consul API. Is it possible somehow attach the token to consul API client? Crypt using old version of consul , hence I cannot send token from environment variable.

**Comment by justmccin** [comment]
> 
@bketelsen #10 @sabir012 
> ``
`
[]() ,`

**Comment by justmccin** [comment]
@https://github.com/golang/vscode-go/blob/408d1993058e45423b01fc514badf6ffbb0f4c73/webpack.config.js#L45

**Comment by justmccin** [comment]
> @https://github.com/golang/vscode-go/blob/408d1993058e45423b01fc514badf6ffbb0f4c73/webpack.config.js#L45

``
